# Generated by Django 5.0.4 on 2024-04-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
